var data = {
    "data": [{
        "id": -1,
        "pId": -2,
        "name": "系统资源",
        "tab_url": "",
        "open": true
    }, {
        "id": 245,
        "pId": 261,
        "name": "用户跟读音频信息",
        "tab_url": "bussiness/tailAudio/showMainView",
        "open": false
    }, {
        "id": 162,
        "pId": 160,
        "name": "搜索",
        "tab_url": "bussiness/questionQuery/showMainView",
        "open": false
    }, {
        "id": 256,
        "pId": 251,
        "name": "积分规则",
        "tab_url": "bussiness/integration/showMainView",
        "open": false
    }, {
        "id": 169,
        "pId": 167,
        "name": "版本升级",
        "tab_url": "bussiness/versionUpgrade/showMainView",
        "open": false
    }, {
        "id": 229,
        "pId": 228,
        "name": "需求指引",
        "tab_url": "requirementHelp",
        "open": true
    }, {
        "id": 181,
        "pId": 179,
        "name": "主题",
        "tab_url": "bussiness/theme/showMainView",
        "open": false
    }, {
        "id": 1,
        "pId": -1,
        "name": "应用需求管理",
        "tab_url": "",
        "open": true,
        "icon": "navicon-round"
    }, {
        "id": 2,
        "pId": 1,
        "name": "全部应用需求总表",
        "tab_url": "allRequirementList",
        "open": true
    }, {
        "id": 3,
        "pId": 1,
        "name": "应用商店需求采集",
        "tab_url": "appRequirementCollect",
        "open": true
    }, {
        "id": 203,
        "pId": -1,
        "name": "应用需求管理 ( PAD )",
        "tab_url": "",
        "open": true,
        "icon": "navicon-round"
    }, {
        "id": 5,
        "pId": 203,
        "name": "应用商店需求采集",
        "tab_url": "appRequirementCollectPad",
        "open": true
    }, {
        "id": 6,
        "pId": 203,
        "name": "全部应用需求总表",
        "tab_url": "allRequirementListPad",
        "open": true
    }, {
        "id": 215,
        "pId": -1,
        "name": "TOP级应用管理",
        "tab_url": "",
        "open": false,
        "icon": "navicon-round"
    }, {
        "id": 9,
        "pId": 215,
        "name": "TOP级应用列表",
        "tab_url": "topAppList",
        "open": false
    }, {
        "id": 12,
        "pId": 215,
        "name": "TOP级应用列表",
        "tab_url": "bussiness/masterActivity/showMainView",
        "open": false
    }, {
        "id": 10,
        "pId": 215,
        "name": "同步应用市场榜单结果",
        "tab_url": "syncAppList",
        "open": false
    }, {
        "id": 11,
        "pId": 215,
        "name": "上传TOP级应用",
        "tab_url": "topAppUpload",
        "open": false
    }, {
        "id": 50,
        "pId": 203,
        "name": "应用商店需求采集",
        "tab_url": "appRequirementCollectPad",
        "open": false
    }, {
        "id": 239,
        "pId": 237,
        "name": "用户播放记录",
        "tab_url": "",
        "open": true
    }, {
        "id": 57,
        "pId": 56,
        "name": "用户积分管理",
        "tab_url": "userIntegral/getUserIntegralView",
        "open": false
    }, {
        "id": 241,
        "pId": 237,
        "name": "应用管理列表",
        "tab_url": "appManageList",
        "open": true
    }, {
        "id": 255,
        "pId": 251,
        "name": "积分领取记录",
        "tab_url": "bussiness/integrationDetail/showMainView",
        "open": false
    }, {
        "id": 7,
        "pId": 205,
        "name": "客服体系需求录入",
        "tab_url": "customRequirementEntryPad",
        "open": true
    }, {
        "id": 8,
        "pId": 205,
        "name": "内容开发需求录入",
        "tab_url": "contentRequirementEntryPad",
        "open": true
    }, {
        "id": 32324,
        "pId": 4,
        "name": "角色管理child",
        "tab_url": "authRole/getAuthRoleMainView",
        "open": false
    }, {
        "id": 193,
        "pId": 39,
        "name": "活动显示图片",
        "tab_url": "activity/showMain",
        "open": false
    }, {
        "id": 4,
        "pId": 205,
        "name": "客服体系需求录入",
        "tab_url": "customRequirementEntry",
        "open": true
    }, {
        "id": 5,
        "pId": 205,
        "name": "内容开发需求录入",
        "tab_url": "contentRequirementEntry",
        "open": true
    }, {
        "id": 249,
        "pId": 261,
        "name": "用户跟读分享记录",
        "tab_url": "bussiness/userTail/showMainView",
        "open": false
    }, {
        "id": 60,
        "pId": 56,
        "name": "积分规则管理",
        "tab_url": "integralRule/getIntegralRuleView",
        "open": false
    }, {
        "id": 164,
        "pId": 160,
        "name": "答题搜答案",
        "tab_url": "bussiness/questionQuery/showMainViewAnswer",
        "open": false
    }, {
        "id": 61,
        "pId": 56,
        "name": "积分行为管理",
        "tab_url": "integralAction/getIntegralActionView",
        "open": false
    }, {
        "id": 202,
        "pId": 160,
        "name": "清除个人搜题",
        "tab_url": "delUserSearch/showMainView",
        "open": false
    }, {
        "id": 82,
        "pId": 42,
        "name": "认证管理",
        "tab_url": "authenticationMachineid/getAuthenticationMachineidView",
        "open": false
    }, {
        "id": 257,
        "pId": 251,
        "name": "连续签到记录",
        "tab_url": "bussiness/integrationSign/showMainView",
        "open": false
    }, {
        "id": 247,
        "pId": 227,
        "name": "用户参与课程",
        "tab_url": "bussiness/userCourse/showMainView",
        "open": false
    }, {
        "id": 136,
        "pId": 56,
        "name": "积分模块管理日志",
        "tab_url": "bussiness/integralDailyLog/getIntegralDailyLogView",
        "open": false
    }, {
        "id": 109,
        "pId": 42,
        "name": "提问信息管理",
        "tab_url": "bussiness/askingProphet/showMainView",
        "open": false
    }, {
        "id": 243,
        "pId": 251,
        "name": "用户签到记录",
        "tab_url": "bussiness/playSign/showMainView",
        "open": false
    }, {
        "id": 233,
        "pId": 227,
        "name": "用户举报信息",
        "tab_url": "bussiness/informer/showMainView",
        "open": false
    }, {
        "id": 259,
        "pId": 251,
        "name": "图片上传",
        "tab_url": "ajaxUpload/showMainView",
        "open": false
    }, {
        "id": 152,
        "pId": 42,
        "name": "用户回答的情况",
        "tab_url": "bussiness/askingProphet/showCustomAnswerMainView",
        "open": false
    }, {
        "id": 41,
        "pId": 39,
        "name": "官方活动记录",
        "tab_url": "activity/showMainView",
        "open": false
    }, {
        "id": 237,
        "pId": -1,
        "name": "应用管理",
        "tab_url": "",
        "open": true,
        "icon": "navicon-round"
    }, {
        "id": 228,
        "pId": -1,
        "name": "帮助菜单",
        "tab_url": "",
        "open": false,
        "icon": "help-circled"
    }, {
        "id": 251,
        "pId": -2,
        "name": "积分管理",
        "tab_url": "",
        "open": false,
        "icon": "navicon-round"
    }, {
        "id": 261,
        "pId": -2,
        "name": "用户跟读管理",
        "tab_url": "",
        "open": false,
        "icon": "navicon-round"
    }, {
        "id": 43,
        "pId": 42,
        "name": "用户基本信息",
        "tab_url": "bussiness/customUserInfo/showMainView",
        "open": false
    }, {
        "id": 44,
        "pId": 42,
        "name": "意见反馈处理",
        "tab_url": "feedback/showMainView",
        "open": false
    }, {
        "id": 198,
        "pId": 42,
        "name": "个人中心",
        "tab_url": "bussiness/userGrade/getUserIntegralView",
        "open": false
    }],
    "errorCode": "101002",
    "errorInfo": ""
}

var user = {
    id: 123,
    name: '管理员',
    role: 'root'
}

export { user, data };
